project:
  type: website
  render:
    - "*.qmd"


  
website:
  title: "Rowan K. O'Hara"
  description-meta: "Personal website for Rowan K. O'Hara showcasing her projects and accomplishments in research and data science."
  
  favicon: img/dna.png
  
  navbar:
    left:
      - href: index.qmd
        text: Home
        aria-label: Home
      - href: projects.qmd
        text: Projects
        aria-label: Projects
      - href: https://drive.google.com/file/d/13Vzbk1a0ixpebof9Hd1wbWHKzLHPgPE3/view?usp=sharing
        text: CV
        aria-label: curriculum vitae
        
    right:
      - href: https://www.linkedin.com/in/rowankohara/
        icon: linkedin
        aria-label: Linkedin
      - href: https://twitter.com/rowankohara
        icon: twitter
        aria-label: Twitter
      - href: https://github.com/rowankohara
        icon: github
        aria-label: GitHub
      - href: mailto:oharark@vcu.edu
        icon: envelope-fill
        aria-label: Email
      
  
  twitter-card:
    creator: "@rowankohara"
  
  open-graph: true
  
  page-footer:
    right: |
      Made with [RStudio](https://www.rstudio.com/) and [Quarto](https://quarto.org/)<br>
      [View the source at GitHub](https://github.com/rowankohara/rowankohara.github.io)

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

