project:
  type: website
  render:
    - "*.qmd"

website:
  title: "Rowan K. O'Hara"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

